"use strict";
// Markdown report rendering. Output is intended to be pasted straight into an
// issue or pull request, so it stays scannable: a verdict, a one-line-per-
// finding table, then the detail.

const { SEVERITY, SEVERITY_ORDER, SEVERITY_BLURB } = require("./util.js");

function location(f) {
  if (!f.file) {
    return "—";
  }
  if (f.line === null) {
    return "`" + f.file + "`";
  }
  return "`" + f.file + ":" + f.line + "`";
}

function escapeCell(text) {
  return String(text).replace(/\|/g, "\\|").replace(/\n+/g, " ");
}

function verdict(findings) {
  const blockers = findings.count("BLOCKER");
  const bugs = findings.count("BUG");
  if (blockers > 0) {
    return {
      label: "Will not load correctly",
      detail:
        blockers +
        " blocker" +
        (blockers === 1 ? "" : "s") +
        " must be fixed before this mod can be expected to work.",
    };
  }
  if (bugs > 0) {
    return {
      label: "Loads, with defects",
      detail:
        "No blockers. " + bugs + " bug" + (bugs === 1 ? "" : "s") + " will affect behaviour.",
    };
  }
  const rest = findings.items.length;
  if (rest === 0) {
    return { label: "Clean", detail: "No findings." };
  }
  return {
    label: "Loads cleanly",
    detail: "No blockers or bugs. " + rest + " item" + (rest === 1 ? "" : "s") + " to consider.",
  };
}

function renderMarkdown(ctx) {
  const F = ctx.findings;
  const info = ctx.modinfo || {};
  const v = verdict(F);
  const lines = [];

  const name = info.display_name || ctx.modName;
  lines.push("# Mod Review — " + name);
  lines.push("");
  lines.push("**Verdict: " + v.label + ".** " + v.detail);
  lines.push("");

  lines.push("| | |");
  lines.push("|---|---|");
  lines.push("| Identifier | `" + (info.identifier || "—") + "` |");
  lines.push("| Version | " + (info.version || "—") + " |");
  lines.push("| Context | " + (info.context || "—") + " |");
  lines.push("| Files reviewed | " + ctx.fileCount + " |");
  if (ctx.shadowCount > 0) {
    lines.push("| Base-game files shadowed | " + ctx.shadowCount + " |");
  }
  lines.push("| Base game | " + (ctx.media ? "`" + ctx.media + "` (" + ctx.mediaSource + ")" : "**not found**") + " |");
  lines.push("| Reviewed | " + ctx.timestamp + " |");
  lines.push("");

  // Counts.
  const present = SEVERITY_ORDER.filter(function (s) {
    return F.count(s) > 0;
  });

  if (present.length === 0) {
    lines.push("No findings. The mod passes every automated check in this review.");
    lines.push("");
    return lines.join("\n");
  }

  lines.push("## Summary");
  lines.push("");
  lines.push("| Severity | Count |");
  lines.push("|---|---|");
  for (const s of present) {
    lines.push("| " + SEVERITY[s] + " | " + F.count(s) + " |");
  }
  lines.push("");

  lines.push("| ID | Severity | Location | Finding |");
  lines.push("|---|---|---|---|");
  for (const s of present) {
    for (const f of F.bySeverity(s)) {
      lines.push(
        "| " +
          f.id +
          " | " +
          SEVERITY[s] +
          " | " +
          escapeCell(location(f)) +
          " | " +
          escapeCell(f.title) +
          " |"
      );
    }
  }
  lines.push("");

  for (const s of present) {
    lines.push("## " + SEVERITY[s]);
    lines.push("");
    lines.push("> " + SEVERITY_BLURB[s]);
    lines.push("");
    for (const f of F.bySeverity(s)) {
      lines.push("### " + f.id + " — " + f.title);
      lines.push("");
      if (f.file) {
        lines.push(
          "**Location:** " +
            location(f) +
            (f.col !== null && f.line !== null ? " (column " + f.col + ")" : "")
        );
        lines.push("");
      }
      if (f.occurrences > 1) {
        lines.push(
          "**Occurrences:** " +
            f.occurrences +
            (f.lines && f.lines.length > 1 ? " (lines " + f.lines.join(", ") + ")" : " in this file")
        );
        lines.push("");
      }
      if (f.detail) {
        lines.push("**Found:** " + f.detail);
        lines.push("");
      }
      if (f.why) {
        lines.push("**Why it matters:** " + f.why);
        lines.push("");
      }
      if (f.fix) {
        lines.push("**Fix:** " + f.fix);
        lines.push("");
      }
      lines.push("<sub>`" + f.check + "`</sub>");
      lines.push("");
    }
  }

  lines.push("---");
  lines.push("");
  lines.push(
    "<sub>Generated by `pa-mod-review`. Findings marked Unverified could not be resolved " +
      "against the bundled references and are not verdicts — they need a human decision.</sub>"
  );
  lines.push("");

  return lines.join("\n");
}

function renderJson(ctx) {
  return JSON.stringify(
    {
      mod: {
        name: ctx.modinfo ? ctx.modinfo.display_name : ctx.modName,
        identifier: ctx.modinfo ? ctx.modinfo.identifier : null,
        version: ctx.modinfo ? ctx.modinfo.version : null,
        context: ctx.modinfo ? ctx.modinfo.context : null,
        root: ctx.modRoot,
      },
      base_game: { path: ctx.media, source: ctx.mediaSource },
      reviewed: ctx.timestamp,
      files_reviewed: ctx.fileCount,
      shadowed_files: ctx.shadowCount,
      verdict: verdict(ctx.findings),
      counts: SEVERITY_ORDER.reduce(function (acc, s) {
        acc[s] = ctx.findings.count(s);
        return acc;
      }, {}),
      findings: ctx.findings.items,
    },
    null,
    2
  );
}

module.exports = { renderMarkdown, renderJson, verdict };
